/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Conceptos.Cliente;
import Conceptos.Mecanico;
import Conceptos.Servicio;
import Conceptos.Solicitud;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import util.ServicioInput;

/**
 * Ventana para atender sobre una solicitud
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
 */
public class VentanaAtender extends javax.swing.JDialog {
    ArrayList<Solicitud> listaDeSolicitudes = new ArrayList<>();
    /**
     * Creates new form VentanaAtender
     */
    public VentanaAtender(java.awt.Frame parent, boolean modal) {       
        super(parent, modal);
        this.setTitle("Atender Solicitudes de Servicio");
        initComponents();
        llenarIniciales();
        
        //Un action listener para ver el cliente seleccionado
        cajaCliente.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e){
                llenarOtrosDatos();
            }
        });
        this.cajaTipoServicio.setEnabled(false);
    }
    
   
    void llenarIniciales(){
        cargarCheckboxDeServicios();
        try(ObjectInputStream input = new ObjectInputStream(new FileInputStream("Data/Solicitudes.dat"))){
            while(true){
                try{
                    //Solicitud s1 = (Solicitud) input.readObject();
                    Cliente c = (Cliente) input.readObject();
                    cajaCliente.addItem(c.getNombre());

                    //listaDeSolicitudes.add(s1);
                }catch(EOFException eof){
                    break;
                } catch(ClassNotFoundException e){
                    e.printStackTrace();
                }
            
        
                }
            }catch(FileNotFoundException e){
                e.printStackTrace();
            }catch(IOException i){
                i.printStackTrace();
            }
        cajaCliente.removeAllItems();
        for(Solicitud s2 : listaDeSolicitudes){
            cajaCliente.addItem(s2.getCliente());
        }
        
        
    
        
        
        
        ArrayList<Mecanico> mecanicos = new ArrayList<>();
        try {
            //Esto usa el archivo de input para meterlo en la lista de clientes
            util.MecanicoInput inputDeMecanicos = new util.MecanicoInput();
            //Abre el archivo
            inputDeMecanicos.abrir();
            
            Mecanico m;
            while ((m = inputDeMecanicos.leer()) != null) {
                mecanicos.add(m);
            }

            inputDeMecanicos.cerrar();
            cajaMecanicos.removeAllItems();
            for (Mecanico mec : mecanicos){

                cajaMecanicos.addItem(mec.getNombre());

            }
    }catch(Exception e){
        
    }
        
        
        cajaEstado.removeAllItems();
        cajaEstado.addItem("Por definir");
        cajaEstado.addItem("Reparado");
        cajaEstado.addItem("En proceso");
    }
    
    
public void cargarCheckboxDeServicios() {
    panelOtrosServicios.removeAll();
    panelOtrosServicios.setLayout(new BoxLayout(panelOtrosServicios, BoxLayout.Y_AXIS));
    ServicioInput input = new ServicioInput();
    
    try {
        input.abrir();
        Servicio s1;

        while ((s1 = input.leer()) != null) {

            JCheckBox check = new JCheckBox(s1.getNombre());

            panelOtrosServicios.add(check);
        }

        input.cerrar();

    } catch (Exception e) {
        e.printStackTrace();
    }

    //recarga el panel
    panelOtrosServicios.revalidate();
    panelOtrosServicios.repaint();
}

    
    private void llenarOtrosDatos(){
        String clienteActual = (String) cajaCliente.getSelectedItem();
        if(clienteActual == null){
            return;
        }
        for(Solicitud s : listaDeSolicitudes){
            if(s.getCliente().equals(clienteActual)){
                espacioPlaca.setText(s.getPlaca());
                
                cajaTipoServicio.setText(s.getServicio());
                
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumServicio = new javax.swing.JLabel();
        cajaCliente = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtTipoServicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cajaMecanicos = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        cajaEstado = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JLabel();
        txtOtrosServicios = new javax.swing.JLabel();
        panelOtrosServicios = new javax.swing.JPanel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        cajaTipoServicio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        espacioPlaca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        txtNumServicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtNumServicio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtNumServicio.setText("Cliente:");

        cajaCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cajaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSalvar.setText("Guardar");

        txtTipoServicio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtTipoServicio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtTipoServicio.setText("Tipo de Servicio:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Mecánico:");

        cajaMecanicos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cajaMecanicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtPlaca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPlaca.setText("Placa:");

        txtEstado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtEstado.setText("Estado:");

        cajaEstado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cajaEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextField1.setText("Este espacio está destinado a comentarios entre el mecánico y el cliente");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        txtObservaciones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtObservaciones.setText("Observaciones:");

        txtOtrosServicios.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtOtrosServicios.setText("Otros Servicios (adicionales):");

        panelOtrosServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout panelOtrosServiciosLayout = new javax.swing.GroupLayout(panelOtrosServicios);
        panelOtrosServicios.setLayout(panelOtrosServiciosLayout);
        panelOtrosServiciosLayout.setHorizontalGroup(
            panelOtrosServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        panelOtrosServiciosLayout.setVerticalGroup(
            panelOtrosServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        btnMas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTipoServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPlaca)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(espacioPlaca)))
                                        .addGap(0, 115, Short.MAX_VALUE))
                                    .addComponent(cajaMecanicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1))
                        .addGap(233, 233, 233))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cajaTipoServicio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOtrosServicios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(panelOtrosServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cajaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPlaca)
                        .addComponent(jLabel2)
                        .addComponent(espacioPlaca))
                    .addComponent(txtNumServicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoServicio)
                    .addComponent(cajaTipoServicio))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cajaMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cajaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstado)))
                .addGap(55, 55, 55)
                .addComponent(txtObservaciones)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtOtrosServicios)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOtrosServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenosActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaAtender dialog = new VentanaAtender(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cajaCliente;
    private javax.swing.JComboBox<String> cajaEstado;
    private javax.swing.JComboBox<String> cajaMecanicos;
    private javax.swing.JLabel cajaTipoServicio;
    private javax.swing.JLabel espacioPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelOtrosServicios;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtNumServicio;
    private javax.swing.JLabel txtObservaciones;
    private javax.swing.JLabel txtOtrosServicios;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JLabel txtTipoServicio;
    // End of variables declaration//GEN-END:variables
}
