/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;
import Conceptos.Cliente;
import Conceptos.Mecanico;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 * @author Jose Rafael Barrantes Quesada
 * Carné: 2025122443
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
*/ 
public class ventanaMecanicos extends javax.swing.JDialog {

    
    ArrayList<Mecanico> mecanicos;
     
    public ventanaMecanicos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        this.setSize(1024,768);
        
        setLayout(null);
        textoID.setBounds(64, 64, 32, 32);
        campoID.setBounds(96, 64, 96, 32);
        textoNombre.setBounds(256, 64, 96, 32);
        campoNombre.setBounds(352, 64, 412, 32);
        textoPuesto.setBounds(256, 112, 96, 32);
        campoPuesto.setBounds(352, 112, 412, 32);
        textoServicios.setBounds(244, 160, 128, 32);
        btnServicios.setBounds(352, 160, 412, 32);
        btAnadirMecanico.setBounds(832, 64, 128, 32);
        eliminarMecanico.setBounds(832, 128, 128, 32);
        modificarMecanico.setBounds(832, 192, 128, 32);
        btnSalir.setBounds(832, 672, 126, 32);
    }

    private void llenarTabla(){
              mecanicos = new ArrayList<>();
        try {
            //Esto usa el archivo de input para meterlo en la lista de clientes
            util.MecanicoInput inputDeMecanicos = new util.MecanicoInput();
            //Abre el archivo
            inputDeMecanicos.abrir();
            
            Mecanico m1;
                while ((m1 = inputDeMecanicos.leer()) != null) {
            mecanicos.add(m1);
            }

            inputDeMecanicos.cerrar();
            
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
        
            columnas.addElement("Identificacion");
            columnas.addElement("Nombre");
            columnas.addElement("Puesto");

            
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
        
            for (Mecanico m2 : mecanicos){
                Vector<String> fila = new Vector<String>();
                fila.addElement(m2.getIdentificacion());
                fila.addElement(m2.getNombre());
                fila.addElement(m2.getPuesto());
            
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.tablaMecanicos.setModel(datos);

        }catch (Exception e) {
            e.printStackTrace();
        }
        /*catch (FileNotFoundException e) {
            e.printStackTrace();
        
        }*/finally{
            
        }

    }

        
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMecanicos = new javax.swing.JTable();
        textoID = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoPuesto = new javax.swing.JLabel();
        btAnadirMecanico = new javax.swing.JButton();
        modificarMecanico = new javax.swing.JButton();
        eliminarMecanico = new javax.swing.JButton();
        campoPuesto = new java.awt.TextField();
        campoID = new java.awt.TextField();
        campoNombre = new java.awt.TextField();
        btnSalir = new javax.swing.JButton();
        textoServicios = new javax.swing.JLabel();
        btnServicios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaMecanicos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tablaMecanicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaMecanicos.setRowHeight(50);
        tablaMecanicos.setRowMargin(3);
        jScrollPane1.setViewportView(tablaMecanicos);

        textoID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoID.setText("ID");

        textoNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoNombre.setText("Nombre");

        textoPuesto.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoPuesto.setText("Puesto");

        btAnadirMecanico.setText("Nuevo");
        btAnadirMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnadirMecanicoActionPerformed(evt);
            }
        });

        modificarMecanico.setText("Modificar");
        modificarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMecanicoActionPerformed(evt);
            }
        });

        eliminarMecanico.setText("Eliminar");
        eliminarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMecanicoActionPerformed(evt);
            }
        });

        campoPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPuestoActionPerformed(evt);
            }
        });

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirsalir(evt);
            }
        });

        textoServicios.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoServicios.setText("Servicios");

        btnServicios.setText("Ver / Editar");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoID)
                        .addGap(20, 20, 20)
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoServicios)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textoPuesto)
                                .addComponent(textoNombre)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(275, 275, 275)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAnadirMecanico)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(eliminarMecanico)
                                .addComponent(modificarMecanico)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAnadirMecanico)
                            .addComponent(textoID)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(textoNombre)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modificarMecanico)
                        .addGap(50, 50, 50)
                        .addComponent(eliminarMecanico))
                    .addComponent(campoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoPuesto)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoServicios)
                            .addComponent(btnServicios))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnSalir)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void limpiarCampos() {
        campoID.setText("");
        campoNombre.setText("");
        campoPuesto.setText("");
        campoID.setEnabled(true); 
        tablaMecanicos.clearSelection(); 
    }

    //guarda el mecanico en el xml
    private void guardarMecanico(){
        try{
            util.MecanicoOutput salidaDeMecanicos = new util.MecanicoOutput();
            salidaDeMecanicos.abrir();
            for(Mecanico m : mecanicos){
                salidaDeMecanicos.escribir(m);
            }
            salidaDeMecanicos.cerrar();
            limpiarCampos();
          
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al modificar el archivo" + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        } 
    }
    
    private void btAnadirMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnadirMecanicoActionPerformed
        String id = campoID.getText();
        String nombre = campoNombre.getText();
        String placa = campoPuesto.getText();

        //Crea una ventana de error si no llena todos los campos
        if (id.isEmpty() || nombre.isEmpty() || placa.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia
            return;
        }

        Mecanico mecanicoNuevo = new Mecanico(id,nombre,placa, new ArrayList<String>());
        mecanicos.add(mecanicoNuevo);
        DefaultTableModel tabla = (DefaultTableModel) tablaMecanicos.getModel();

        Vector<String> filaNueva = new Vector<>();
        filaNueva.add(id);
        filaNueva.add(nombre);
        filaNueva.add(placa);

        tabla.addRow(filaNueva);
        //guarda el mecanico nuevo en el xml
        guardarMecanico();

        javax.swing.JOptionPane.showMessageDialog(this, "Mecanico añadido.");
    }//GEN-LAST:event_btAnadirMecanicoActionPerformed

    private void modificarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMecanicoActionPerformed
        int filaEscogida = tablaMecanicos.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un mecanico con el mouse");
            return;
        }

        Mecanico mecanicoPorModificar = mecanicos.get(filaEscogida);

        String idNuevo = campoID.getText().trim();
        String nombreNuevo = campoNombre.getText().trim();
        String placaNueva = campoPuesto.getText().trim();


        if (idNuevo.isEmpty() || nombreNuevo.isEmpty() || placaNueva.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia.
            return;
        }

        mecanicoPorModificar.setIdentificacion(idNuevo);
        mecanicoPorModificar.setNombre(nombreNuevo);
        mecanicoPorModificar.setPuesto(placaNueva);


        DefaultTableModel tabla = (DefaultTableModel) tablaMecanicos.getModel();

        tabla.setValueAt(idNuevo, filaEscogida, 0);
        tabla.setValueAt(nombreNuevo, filaEscogida, 1);
        tabla.setValueAt(placaNueva, filaEscogida, 2);

        guardarMecanico();

        javax.swing.JOptionPane.showMessageDialog(this, "Mecanico modificado.");
    }//GEN-LAST:event_modificarMecanicoActionPerformed

    private void eliminarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMecanicoActionPerformed
        //Uno puede seleccionar filas con el mouse, entonces elimina
        //la fila que seleccione
        int filaEscogida = tablaMecanicos.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un mecanico con el mouse");
            return;
        }
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Quiere eliminar el mecanico seleccionado?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            //elimina en el array
            mecanicos.remove(filaEscogida);

            //elimina en la tabla
            DefaultTableModel tabla = (DefaultTableModel) tablaMecanicos.getModel();
            tabla.removeRow(filaEscogida);

            //cambia el XML
            guardarMecanico();
            javax.swing.JOptionPane.showMessageDialog(this, "Mecanico eliminado exitosamente.");
        }
    }//GEN-LAST:event_eliminarMecanicoActionPerformed

    private void campoPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPuestoActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void btnSalirsalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirsalir
        //Sale de la ventana
        setVisible(false);
    }//GEN-LAST:event_btnSalirsalir

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        int filaEscogida = tablaMecanicos.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un mecanico con el mouse");
            return;
        }
        
        Mecanico mecanico = mecanicos.get(filaEscogida);
               
        VentanaCheckServicios ventanaCheckServicios = new VentanaCheckServicios(this, true, mecanico, mecanicos);
        ventanaCheckServicios.setVisible(true);
    }//GEN-LAST:event_btnServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaMecanicos dialog = new ventanaMecanicos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnadirMecanico;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicios;
    private java.awt.TextField campoID;
    private java.awt.TextField campoNombre;
    private java.awt.TextField campoPuesto;
    private javax.swing.JButton eliminarMecanico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarMecanico;
    private javax.swing.JTable tablaMecanicos;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPuesto;
    private javax.swing.JLabel textoServicios;
    // End of variables declaration//GEN-END:variables

}