/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Conceptos.Cliente;
import Conceptos.Servicio;
import Conceptos.Solicitud;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import util.ClienteInput;
import util.ServicioInput;
import util.SolicitudOutput;

/**
 * Ventana para realizar una solicitud
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
 */
public class VentanaSolicitar extends javax.swing.JDialog {

    private ArrayList<String> listaClientes = new ArrayList<>();
    private ArrayList<String> listaServicios = new ArrayList<>();
    /**
     * Creates new form VentanaSolicitar
     */
    public VentanaSolicitar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Crear Solicitud de Servicio");
        initComponents();
        llenarInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        txtPlaca = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        espacioPlaca = new javax.swing.JTextField();
        txtCliente = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JLabel();
        cajaClientes = new javax.swing.JComboBox<>();
        txtServicios = new javax.swing.JLabel();
        cajaServicios = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        comentarioEnInterfazGrafica = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaObservaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        txtPlaca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPlaca.setText("Placa");

        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Guardar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        espacioPlaca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txtCliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCliente.setText("Cliente");

        txtObservaciones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtObservaciones.setText("Observaciones");

        cajaClientes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cajaClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtServicios.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtServicios.setText("Tipo de Servicio");

        cajaServicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comentarioEnInterfazGrafica.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        comentarioEnInterfazGrafica.setText("<--- No sé que hace este botón");

        cajaObservaciones.setColumns(20);
        cajaObservaciones.setRows(5);
        jScrollPane1.setViewportView(cajaObservaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtObservaciones)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlaca)
                            .addComponent(txtCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espacioPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtServicios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(comentarioEnInterfazGrafica)))
                        .addGap(112, 112, 112)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicios)
                    .addComponent(espacioPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente)
                    .addComponent(cajaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(comentarioEnInterfazGrafica))
                .addGap(67, 67, 67)
                .addComponent(txtObservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarInicial(){
        ServicioInput inputDeServicios = new ServicioInput();
        ClienteInput inputDeClientes = new ClienteInput();
        //Por algun motivo, la lista empieza con items del 1 al 4,
        //se borran al iniciar
        cajaServicios.removeAllItems();
        cajaClientes.removeAllItems();
        Servicio s1;
        Cliente c1;
        
        
        try{
            inputDeServicios.abrir();
            while((s1 = inputDeServicios.leer()) != null){
                cajaServicios.addItem(s1.getNombre());
            }
            inputDeServicios.cerrar();
            
            inputDeClientes.abrir();
            while((c1 = inputDeClientes.leer()) != null){
                //Aca anado que tambien se extraiga la id, porque sino
                //despues es un dolor
                String clienteConId = c1.getNombre() + " ("+c1.getId()+")";
                cajaClientes.addItem(clienteConId);
            }
            inputDeClientes.cerrar();
            
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //Como el cliente se le pega el id, esto lo separa
    //basado en una de las respuestas
    //https://stackoverflow.com/questions/24256478/pattern-to-extract-text-between-parenthesis
    private String extraerIdCliente(String clienteConId){
        
        String soloLaId = clienteConId.substring(clienteConId.indexOf("(")+1, clienteConId.indexOf(")"));
        return soloLaId;
    }
    
    
    private String extraerNombreCliente(String clienteConId){
        String soloElNombre = clienteConId.substring(0,clienteConId.indexOf("(")-1);
        return soloElNombre;
    }
    
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Su solicitud ha sido ingresada exitosamente,\nNúmero _____" + "", "Número de Servicio", JOptionPane.INFORMATION_MESSAGE);
        //Se extraen los datos de los campos
        
        //Se usa .trim para que no se pongan espacios ni nada extra
        String placa = espacioPlaca.getText().trim();
        String cliente = cajaClientes.getSelectedItem().toString();
        String servicio = cajaServicios.getSelectedItem().toString();
        String observaciones = cajaObservaciones.getText();
        
        String nombreCliente = extraerNombreCliente(cliente);
        String identificacion = extraerIdCliente(cliente);
        //Para que no pueda dejar nada vacio
        if(placa.isEmpty() || observaciones.isEmpty()){
            JOptionPane.showMessageDialog(this,"No puede dejar campos vacios");
        }
        
        //Hay que crear un objeto solicitud para añadirlo
        Solicitud solicitudNueva = new Solicitud(placa,nombreCliente,servicio,observaciones,identificacion);
        
        SolicitudOutput outputDeSolicitud = new SolicitudOutput();
        
        try{
            outputDeSolicitud.abrir();
            outputDeSolicitud.escribir(solicitudNueva);
            outputDeSolicitud.cerrar();
        
        } catch (Exception e){
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private void cajaServicios(java.awt.event.ActionEvent evt){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaSolicitar dialog = new VentanaSolicitar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cajaClientes;
    private javax.swing.JTextArea cajaObservaciones;
    private javax.swing.JComboBox<String> cajaServicios;
    private javax.swing.JLabel comentarioEnInterfazGrafica;
    private javax.swing.JTextField espacioPlaca;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtObservaciones;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JLabel txtServicios;
    // End of variables declaration//GEN-END:variables
}
