/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;
import Conceptos.Servicio;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 * @author Jose Rafael Barrantes Quesada
 * Carné: 2025122443
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
*/ 
public class ventanaServicios extends javax.swing.JDialog {

    
    ArrayList<Servicio> servicios;
     
    public ventanaServicios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        this.setSize(1024,768);
        
        setLayout(null);
        textoID.setBounds(64, 64, 32, 32);
        campoID.setBounds(96, 64, 96, 32);
        textoNombre.setBounds(256, 64, 96, 32);
        campoNombre.setBounds(352, 64, 412, 32);
        textoPrecio.setBounds(256, 112, 64, 32);
        campoPrecio.setBounds(352, 112, 256, 32);
        btAnadirServicio.setBounds(832, 64, 128, 32);
        eliminarServicio.setBounds(832, 128, 128, 32);
        modificarServicio.setBounds(832, 192, 128, 32);
        btnSalir.setBounds(832, 672, 126, 32);
    }

    private void llenarTabla(){
      
        try {
            servicios = util.ServiciosCargadorXML.Cargar("Export/servicios.xml");
            
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
        
            columnas.addElement("Identificacion");
            columnas.addElement("Nombre");
            columnas.addElement("Precio");

            
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
        
            for (Servicio s : servicios){
                Vector<String> fila = new Vector<String>();
                fila.addElement(s.getIdentificacion());
                fila.addElement(s.getNombre());
                fila.addElement("₡" + s.getPrecio());
            
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.tablaServicios.setModel(datos);

        }/*catch (FileNotFoundException e) {
            e.printStackTrace();
        /*catch (FileNotFoundException e) {
            e.printStackTrace();
        
        }*/finally{
            
        }

    }

        
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        textoID = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoPrecio = new javax.swing.JLabel();
        btAnadirServicio = new javax.swing.JButton();
        modificarServicio = new javax.swing.JButton();
        eliminarServicio = new javax.swing.JButton();
        campoPrecio = new java.awt.TextField();
        campoID = new java.awt.TextField();
        campoNombre = new java.awt.TextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 768));

        tablaServicios.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaServicios.setRowHeight(50);
        tablaServicios.setRowMargin(3);
        jScrollPane1.setViewportView(tablaServicios);

        textoID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoID.setText("ID");

        textoNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoNombre.setText("Nombre");

        textoPrecio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoPrecio.setText("Precio");

        btAnadirServicio.setText("Nuevo");
        btAnadirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnadirServicioActionPerformed(evt);
            }
        });

        modificarServicio.setText("Modificar");
        modificarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarServicioActionPerformed(evt);
            }
        });

        eliminarServicio.setText("Eliminar");
        eliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarServicioActionPerformed(evt);
            }
        });

        campoPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        campoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioActionPerformed(evt);
            }
        });

        campoID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        campoNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoID)
                        .addGap(20, 20, 20)
                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoNombre)
                            .addComponent(textoPrecio))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAnadirServicio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(eliminarServicio)
                        .addComponent(modificarServicio)))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnadirServicio)
                    .addComponent(textoID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(modificarServicio))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textoNombre)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(eliminarServicio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoPrecio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnSalir)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void limpiarCampos() {
        campoID.setText("");
        campoNombre.setText("");
        campoPrecio.setText("");
        campoID.setEnabled(true);
        tablaServicios.clearSelection(); 
    }

    //guarda el mecanico en el xml
    private void guardarServicio(){
        try{
            util.nuevoServicioAlXML.GuardarServicios(servicios,"Export/servicios.xml");
            limpiarCampos();
          
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al modificar el archivo" + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        } 
    }
    
    private void btAnadirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnadirServicioActionPerformed
        String id = campoID.getText();
        String nombre = campoNombre.getText();
        String precio = campoPrecio.getText();

        //Crea una ventana de error si no llena todos los campos
        if (id.isEmpty() || nombre.isEmpty() || precio.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia
            return;
        }

        Servicio servicioNuevo = new Servicio(id,nombre,precio);
        servicios.add(servicioNuevo);
        DefaultTableModel tabla = (DefaultTableModel) tablaServicios.getModel();

        Vector<String> filaNueva = new Vector<>();
        filaNueva.add(id);
        filaNueva.add(nombre);
        filaNueva.add("₡" + precio);

        tabla.addRow(filaNueva);
        //guarda el servicio nuevo en el xml
        guardarServicio();

        javax.swing.JOptionPane.showMessageDialog(this, "Servicio añadido.");
    }//GEN-LAST:event_btAnadirServicioActionPerformed

    private void modificarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarServicioActionPerformed
        int filaEscogida = tablaServicios.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un servicio con el mouse");
            return;
        }

        Servicio servicioPorModificar = servicios.get(filaEscogida);

        String idNuevo = campoID.getText().trim();
        String nombreNuevo = campoNombre.getText().trim();
        String precioNuevo = campoPrecio.getText().trim();


        if (idNuevo.isEmpty() || nombreNuevo.isEmpty() || precioNuevo.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia.
            return;
        }

        servicioPorModificar.setIdentificacion(idNuevo);
        servicioPorModificar.setNombre(nombreNuevo);
        servicioPorModificar.setPrecio(precioNuevo);


        DefaultTableModel tabla = (DefaultTableModel) tablaServicios.getModel();

        tabla.setValueAt(idNuevo, filaEscogida, 0);
        tabla.setValueAt(nombreNuevo, filaEscogida, 1);
        tabla.setValueAt(precioNuevo, filaEscogida, 2);

        guardarServicio();

        javax.swing.JOptionPane.showMessageDialog(this, "Mecanico modificado.");
    }//GEN-LAST:event_modificarServicioActionPerformed

    private void eliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarServicioActionPerformed
        //Uno puede seleccionar filas con el mouse, entonces elimina
        //la fila que seleccione
        int filaEscogida = tablaServicios.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un servicio con el mouse");
            return;
        }
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Quiere eliminar el servicio seleccionado?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            //elimina en el array
            servicios.remove(filaEscogida);

            //elimina en la tabla
            DefaultTableModel tabla = (DefaultTableModel) tablaServicios.getModel();
            tabla.removeRow(filaEscogida);

            //cambia el XML
            guardarServicio();
            javax.swing.JOptionPane.showMessageDialog(this, "Servicio eliminado exitosamente.");
        }
    }//GEN-LAST:event_eliminarServicioActionPerformed
                                            
    private void campoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir
        //Sale de la ventana
        setVisible(false);
    }//GEN-LAST:event_salir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaServicios dialog = new ventanaServicios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnadirServicio;
    private javax.swing.JButton btnSalir;
    private java.awt.TextField campoID;
    private java.awt.TextField campoNombre;
    private java.awt.TextField campoPrecio;
    private javax.swing.JButton eliminarServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarServicio;
    private javax.swing.JTable tablaServicios;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPrecio;
    // End of variables declaration//GEN-END:variables

}