/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 * @author Jose Rafael Barrantes Quesada
 * Carné: 2025122443
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
*/ 
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        this.setSize(1024,768);
        setExtendedState(Escritorio.MAXIMIZED_BOTH);
        
        setLayout(null);
        botonClientes.setBounds(80, 272, 144, 144);
        botonServicios.setBounds(440, 272, 144, 144);
        botonMecanicos.setBounds(800, 272, 144, 144);
        textoClientes.setBounds(80, 416, 144, 32);
        textoServicios.setBounds(440, 416, 144, 32);
        textoMecanicos.setBounds(800, 416, 144, 32);
        titulo1.setBounds(64, 64, 1024, 64);
        titulo2.setBounds(100, 128, 1024, 64);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMecanicos = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        textoServicios = new javax.swing.JLabel();
        botonServicios = new javax.swing.JButton();
        textoClientes = new javax.swing.JLabel();
        textoMecanicos = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        botonMecanicos.setBackground(new java.awt.Color(255, 255, 255));
        botonMecanicos.setForeground(new java.awt.Color(0, 0, 0));
        botonMecanicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoMecanicos.jpg"))); // NOI18N
        botonMecanicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonMecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMecanicosActionPerformed(evt);
            }
        });

        botonClientes.setBackground(new java.awt.Color(255, 255, 255));
        botonClientes.setForeground(new java.awt.Color(0, 0, 0));
        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoClientes.jpg"))); // NOI18N
        botonClientes.setAlignmentY(0.0F);
        botonClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonClientes.setMaximumSize(new java.awt.Dimension(144, 144));
        botonClientes.setMinimumSize(new java.awt.Dimension(144, 144));
        botonClientes.setPreferredSize(new java.awt.Dimension(144, 144));
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        textoServicios.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textoServicios.setForeground(new java.awt.Color(0, 0, 0));
        textoServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoServicios.setText("Servicios");
        textoServicios.setToolTipText("");
        textoServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textoServicios.setMaximumSize(new java.awt.Dimension(144, 32));
        textoServicios.setMinimumSize(new java.awt.Dimension(144, 32));
        textoServicios.setPreferredSize(new java.awt.Dimension(144, 32));

        botonServicios.setBackground(new java.awt.Color(238, 238, 238));
        botonServicios.setForeground(new java.awt.Color(0, 0, 0));
        botonServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoServicios.jpg"))); // NOI18N
        botonServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        botonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonServiciosActionPerformed(evt);
            }
        });

        textoClientes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textoClientes.setForeground(new java.awt.Color(0, 0, 0));
        textoClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoClientes.setText("Clientes");
        textoClientes.setToolTipText("");
        textoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textoClientes.setMaximumSize(new java.awt.Dimension(144, 32));
        textoClientes.setMinimumSize(new java.awt.Dimension(144, 32));
        textoClientes.setPreferredSize(new java.awt.Dimension(144, 32));

        textoMecanicos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textoMecanicos.setForeground(new java.awt.Color(0, 0, 0));
        textoMecanicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoMecanicos.setText("Mecánicos");
        textoMecanicos.setToolTipText("");
        textoMecanicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textoMecanicos.setMaximumSize(new java.awt.Dimension(144, 32));
        textoMecanicos.setMinimumSize(new java.awt.Dimension(144, 32));
        textoMecanicos.setPreferredSize(new java.awt.Dimension(144, 32));

        titulo1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        titulo1.setText("BIENVENIDO AL ADMINISTRADOR");

        titulo2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        titulo2.setText("DEL TALLER ~ALEX BARBOZA~");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo2))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)
                                .addComponent(botonServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMecanicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoMecanicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMecanicosActionPerformed
        ventanaMecanicos mecanicos = new ventanaMecanicos(Escritorio.this,true);
        
        mecanicos.setVisible(true);
    }//GEN-LAST:event_botonMecanicosActionPerformed

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        ventanaClientes clientes = new ventanaClientes(Escritorio.this,true);
        
        clientes.setVisible(true);
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonServiciosActionPerformed
        ventanaServicios servicios = new ventanaServicios(Escritorio.this,true);
        
        servicios.setVisible(true);
    }//GEN-LAST:event_botonServiciosActionPerformed
    

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonMecanicos;
    private javax.swing.JButton botonServicios;
    private javax.swing.JLabel textoClientes;
    private javax.swing.JLabel textoMecanicos;
    private javax.swing.JLabel textoServicios;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
