/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;
import Conceptos.Clientes;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 * Ventana con una tabla de los clientes del establecimiento
 * @author Jose Rafael Barrantes Quesada
 * Carné: 2025122443
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
 */
public class ventanaClientes extends javax.swing.JDialog {

    
    ArrayList<Clientes> clientes;
     
    public ventanaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    
        llenarTabla();
        this.setSize(1024,768);
        
        setLayout(null);
        textoID.setBounds(64, 64, 32, 32);
        campoID.setBounds(96, 64, 128, 32);
        textoPlaca.setBounds(32, 112, 64, 32);
        campoPlaca.setBounds(96, 112, 128, 32);
        textoNombre.setBounds(256, 64, 96, 32);
        campoNombre.setBounds(352, 64, 412, 32);
        textoTelefono.setBounds(256, 112, 96, 32);
        campoTelefono.setBounds(352, 112, 256, 32);
        textoEmail.setBounds(256, 160, 64, 32);
        campoEmail.setBounds(352, 160, 412, 32);
        btAnadirCliente.setBounds(832, 64, 128, 32);
        eliminarClientes.setBounds(832, 128, 128, 32);
        modificarCliente.setBounds(832, 192, 128, 32);
        btnSalir.setBounds(832, 672, 126, 32);
    }

    private void llenarTabla(){
      
        try {
            clientes = util.CargadorXML.Cargar("Data/clientes.xml");
            
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
        
            columnas.addElement("ID");
            columnas.addElement("Nombre");
            columnas.addElement("Teléfono");
            columnas.addElement("Placa");
            columnas.addElement("Email");
            
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
        
            for (Clientes c : clientes){
                Vector<String> fila = new Vector<String>();
                fila.addElement(c.getId());
                fila.addElement(c.getNombre());
                fila.addElement(c.getTelefono());
                fila.addElement(c.getPlaca());
                fila.addElement(c.getEmail());
            
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.jTable1.setModel(datos);

        }/*catch (FileNotFoundException e) {
            e.printStackTrace();
        
        }*/finally{
            
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        campoPlaca = new java.awt.TextField();
        campoEmail = new java.awt.TextField();
        campoID = new java.awt.TextField();
        campoNombre = new java.awt.TextField();
        campoTelefono = new java.awt.TextField();
        textoID = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoPlaca = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JLabel();
        btAnadirCliente = new javax.swing.JButton();
        modificarCliente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        eliminarClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jTable1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setRowHeight(50);
        jTable1.setRowMargin(2);
        jScrollPane1.setViewportView(jTable1);

        campoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPlacaActionPerformed(evt);
            }
        });

        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoActionPerformed(evt);
            }
        });

        textoID.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoID.setText("ID");

        textoEmail.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoEmail.setText("Email");

        textoPlaca.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoPlaca.setText("Placa");

        textoNombre.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoNombre.setText("Nombre");

        textoTelefono.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoTelefono.setText("Telefono");

        btAnadirCliente.setText("Nuevo");
        btAnadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnadirClienteActionPerformed(evt);
            }
        });

        modificarCliente.setText("Modificar");
        modificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClienteActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        eliminarClientes.setText("Eliminar");
        eliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoTelefono)
                        .addGap(20, 20, 20)
                        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoID)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(textoNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoEmail)
                                .addGap(35, 35, 35)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAnadirCliente)
                    .addComponent(modificarCliente)
                    .addComponent(eliminarClientes))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(textoPlaca)
                    .addContainerGap(926, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(textoID)))
                        .addGap(74, 74, 74)
                        .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textoNombre)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAnadirCliente)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textoTelefono)
                                .addGap(8, 8, 8))
                            .addComponent(modificarCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEmail)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(eliminarClientes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(242, 242, 242)
                    .addComponent(textoPlaca)
                    .addContainerGap(502, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPlacaActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoActionPerformed

    
   //Para añadir nuevos clientes
    private void btAnadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnadirClienteActionPerformed
        String id = campoID.getText();
        String nombre = campoNombre.getText();
        String placa = campoPlaca.getText();
        String telefono = campoTelefono.getText();
        String email = campoEmail.getText();
        //Crea una ventana de error si no llena todos los campos
        if (id.isEmpty() || nombre.isEmpty() || placa.isEmpty() || telefono.isEmpty() || email.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia
            return;
        }
        
        Clientes clienteNuevo = new Clientes(id,nombre,placa,telefono,email);
        clientes.add(clienteNuevo);
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        
        Vector<String> filaNueva = new Vector<>();
        filaNueva.add(id);
        filaNueva.add(nombre);
        filaNueva.add(telefono);
        filaNueva.add(placa);
        filaNueva.add(email);
        
        tabla.addRow(filaNueva);
        //guarda el cliente nuevo en el xml
        guardarCliente();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente añadido.");
    }//GEN-LAST:event_btAnadirClienteActionPerformed
    
    //Dos propositos: vacia los campos al eliminar un cliente, si no se hace,
    //no se elimina del XML
    //Tambien los limpia al crear un nuevo cliente, por si habia un valor basura
    //o algo
    private void limpiarCampos() {
        campoID.setText("");
        campoNombre.setText("");
        campoTelefono.setText("");
        campoPlaca.setText("");
        campoEmail.setText("");
        campoID.setEnabled(true); 
        jTable1.clearSelection(); 
    }

    //guarda el cliente en el xml
    private void guardarCliente(){
        try{
            util.nuevoClienteAlXML.GuardarClientes(clientes,"Data/clientes.xml");
            limpiarCampos();
          
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al modificar el archivo" + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        } 
    }
    private void modificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClienteActionPerformed
        int filaEscogida = jTable1.getSelectedRow();
        
        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un cliente con el mouse");
            return;
        }
        
        Clientes clientePorModificar = clientes.get(filaEscogida);
        
        String idNuevo = campoID.getText().trim();
        String nombreNuevo = campoNombre.getText().trim();
        String placaNueva = campoPlaca.getText().trim();
        String telefonoNuevo = campoTelefono.getText().trim();
        String emailNuevo = campoEmail.getText().trim();
        
        if (idNuevo.isEmpty() || nombreNuevo.isEmpty() || placaNueva.isEmpty() || telefonoNuevo.isEmpty() || emailNuevo.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia.
            return;
        }
        
        clientePorModificar.setId(idNuevo);
        clientePorModificar.setNombre(nombreNuevo);
        clientePorModificar.setPlaca(placaNueva);
        clientePorModificar.setTelefono(telefonoNuevo);
        clientePorModificar.setEmail(emailNuevo);
        
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        
        tabla.setValueAt(idNuevo, filaEscogida, 0);
        tabla.setValueAt(nombreNuevo, filaEscogida, 1);
        tabla.setValueAt(placaNueva, filaEscogida, 2);
        tabla.setValueAt(telefonoNuevo, filaEscogida, 3);
        tabla.setValueAt(emailNuevo, filaEscogida, 4);
        
        guardarCliente();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente modificado.");
    }//GEN-LAST:event_modificarClienteActionPerformed
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Sale de la ventana
        setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void eliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesActionPerformed
        //Uno puede seleccionar filas con el mouse, entonces elimina
        //la fila que seleccione
        int filaEscogida = jTable1.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar una fila con el mouse");
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un cliente con el mouse");
            return;
        }
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Quiere eliminar el cliente seleccionado?", 
            "Confirmar", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            //elimina en el array
            clientes.remove(filaEscogida);

            //elimina en la tabla
            DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
            tabla.removeRow(filaEscogida);

            //cambia el XML
            guardarCliente();
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.");
        }                                                

    }//GEN-LAST:event_eliminarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaClientes dialog = new ventanaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnadirCliente;
    private javax.swing.JButton btnSalir;
    private java.awt.TextField campoEmail;
    private java.awt.TextField campoID;
    private java.awt.TextField campoNombre;
    private java.awt.TextField campoPlaca;
    private java.awt.TextField campoTelefono;
    private javax.swing.JButton eliminarClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarCliente;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoID;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoPlaca;
    private javax.swing.JLabel textoTelefono;
    // End of variables declaration//GEN-END:variables
}
