/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;
import Conceptos.Servicios;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 * @author Jose Rafael Barrantes Quesada
 * Carné: 2025122443
 * @author Ian Alexander Valerio Steller
 * Carné: 2025085826
*/ 
public class ventanaServicios extends javax.swing.JDialog {

    
    ArrayList<Servicios> servicios;
     
    public ventanaServicios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        this.setSize(1024,768);
    }

    private void llenarTabla(){
      
        try {
            servicios = util.ServiciosCargadorXML.Cargar("Data/servicios.xml");
            
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
        
            columnas.addElement("Identificacion");
            columnas.addElement("Nombre");
            columnas.addElement("Puesto");

            
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
        
            for (Servicios s : servicios){
                Vector<String> fila = new Vector<String>();
                fila.addElement(s.getIdentificacion());
                fila.addElement(s.getNombre());
                fila.addElement(s.getPrecio());
            
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.tablaServicios.setModel(datos);

        }/*catch (FileNotFoundException e) {
            e.printStackTrace();
        
        }*/finally{
            
        }

    }

        
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btAnadirServicio = new javax.swing.JButton();
        modificarServicio = new javax.swing.JButton();
        eliminarServicio = new javax.swing.JButton();
        campoPrecio = new java.awt.TextField();
        campoID = new java.awt.TextField();
        campoNombre = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaServicios.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaServicios.setRowHeight(50);
        tablaServicios.setRowMargin(3);
        jScrollPane1.setViewportView(tablaServicios);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Precio");

        btAnadirServicio.setText("Anadir Servicio");
        btAnadirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnadirServicioActionPerformed(evt);
            }
        });

        modificarServicio.setText("Modificar");
        modificarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarServicioActionPerformed(evt);
            }
        });

        eliminarServicio.setText("Eliminar");
        eliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarServicioActionPerformed(evt);
            }
        });

        campoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioActionPerformed(evt);
            }
        });

        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(239, 239, 239))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(29, 29, 29)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAnadirServicio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(eliminarServicio)
                        .addComponent(modificarServicio)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnadirServicio)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(modificarServicio))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(eliminarServicio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        private void limpiarCampos() {
        campoID.setText("");
        campoNombre.setText("");
        campoPrecio.setText("");
        campoID.setEnabled(true); 
        tablaServicios.clearSelection(); 
    }

    //guarda el mecanico en el xml
    private void guardarServicio(){
        try{
            util.nuevoServicioAlXML.GuardarServicios(servicios,"Data/servicios.xml");
            limpiarCampos();
          
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al modificar el archivo" + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        } 
    }
    
    private void btAnadirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnadirServicioActionPerformed
        String id = campoID.getText();
        String nombre = campoNombre.getText();
        String precio = campoPrecio.getText();

        //Crea una ventana de error si no llena todos los campos
        if (id.isEmpty() || nombre.isEmpty() || precio.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia
            return;
        }

        Servicios servicioNuevo = new Servicios(id,nombre,precio);
        servicios.add(servicioNuevo);
        DefaultTableModel tabla = (DefaultTableModel) tablaServicios.getModel();

        Vector<String> filaNueva = new Vector<>();
        filaNueva.add(id);
        filaNueva.add(nombre);
        filaNueva.add(precio);

        tabla.addRow(filaNueva);
        //guarda el servicio nuevo en el xml
        guardarServicio();

        javax.swing.JOptionPane.showMessageDialog(this, "Servicio añadido.");
    }//GEN-LAST:event_btAnadirServicioActionPerformed

    private void modificarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarServicioActionPerformed
        int filaEscogida = tablaServicios.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un servicio con el mouse");
            return;
        }

        Servicios servicioPorModificar = servicios.get(filaEscogida);

        String idNuevo = campoID.getText().trim();
        String nombreNuevo = campoNombre.getText().trim();
        String precioNuevo = campoPrecio.getText().trim();


        if (idNuevo.isEmpty() || nombreNuevo.isEmpty() || precioNuevo.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos","Error01",javax.swing.JOptionPane.ERROR_MESSAGE);
            //Es importante el return porque si no, igual se crea la fila, solo que vacia.
            return;
        }

        servicioPorModificar.setIdentificacion(idNuevo);
        servicioPorModificar.setNombre(nombreNuevo);
        servicioPorModificar.setPrecio(precioNuevo);


        DefaultTableModel tabla = (DefaultTableModel) tablaServicios.getModel();

        tabla.setValueAt(idNuevo, filaEscogida, 0);
        tabla.setValueAt(nombreNuevo, filaEscogida, 1);
        tabla.setValueAt(precioNuevo, filaEscogida, 2);

        guardarServicio();

        javax.swing.JOptionPane.showMessageDialog(this, "Mecanico modificado.");
    }//GEN-LAST:event_modificarServicioActionPerformed

    private void eliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarServicioActionPerformed
        //Uno puede seleccionar filas con el mouse, entonces elimina
        //la fila que seleccione
        int filaEscogida = tablaServicios.getSelectedRow();

        //Si no escoge una fila
        if(filaEscogida == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe seleccionar un servicio con el mouse");
            return;
        }
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Quiere eliminar el servicio seleccionado?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            //elimina en el array
            servicios.remove(filaEscogida);

            //elimina en la tabla
            DefaultTableModel tabla = (DefaultTableModel) tablaServicios.getModel();
            tabla.removeRow(filaEscogida);

            //cambia el XML
            guardarServicio();
            javax.swing.JOptionPane.showMessageDialog(this, "Servicio eliminado exitosamente.");
        }
    }//GEN-LAST:event_eliminarServicioActionPerformed

    private void campoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaServicios dialog = new ventanaServicios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnadirServicio;
    private java.awt.TextField campoID;
    private java.awt.TextField campoNombre;
    private java.awt.TextField campoPrecio;
    private javax.swing.JButton eliminarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarServicio;
    private javax.swing.JTable tablaServicios;
    // End of variables declaration//GEN-END:variables

}